spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musicapi?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        bytecode:
          show_sql: true
          format_sql: true
          highlight_sql: true
  mvc:
    static-path-pattern: /swagger*
    path match:
      matching-strategy: ant_path_matcher
springdoc:
  swagger-ui:
    path: /swagger-ui.html




